[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
        [plugins.inputs]
        # The base url of your site (optional, default = main URL set in Netlify)
        # scottt baseUrl = "https://example.com"
        # Path to the sitemap URL (optional, default = /sitemap.xml)
        #scott sitemapPath = "/sitemap.xml"
        # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
        providers = [
                "google",
                "bing",
                "yandex"
        ]

